[sm2]
ef_initial       = 2.5
ef_min           = 1.3
ef_coef_a        = 0.1
ef_coef_b        = 0.08
ef_coef_c        = 0.02
interval_first   = 1
interval_second  = 6

graduate_min_rep  = 3
graduate_max_intv = 5
graduate_min_ef   = 2.3